config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  resources :snippets do
    resources :snippets
    resources :comments
    member do
      put 'vote', to: "snippets#like"
      put 'unvote', to: "snippets#unlike"
      put 'outdated', to: "snippets#like"
      put 'notoutdated', to: "snippets#unlike"
    end
  end

  post 'flag/:id', to: 'snippets#flag', as: 'flag_snippet'
  
  devise_for :users, controllers: {registrations: 'registrations'}
  root 'snippets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :snippet
  belongs_to :user
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :user
  belongs_to :snippet, optional: true
  has_many :comments, dependent: :destroy
  has_many :snippets
  is_impressionable
  acts_as_votable
  has_many :snippet_tags
  has_many :tags, through: :snippet_tags
end

app/models/snippet_tag.rb
class SnippetTag < ApplicationRecord
  belongs_to :tag
  belongs_to :snippet
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :snippet_tags
    has_many :snippets, through: :snippet_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :snippets
  has_many :comments, dependent: :destroy
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @snippet = Snippet.find(params[:snippet_id])
    @comment = @snippet.comments.create(comment_params)
    @comment.user_id = current_user.id if current_user
    @comment.name = current_user.name if current_user
    @comment.save!

    redirect_to snippet_path(@snippet)

  end

  def destroy
    @snippet = Snippet.find(params[:snippet_id])
    @comment = @snippet.comments.find(params[:id])
    @comment.destroy
    redirect_to snippet_path(@snippet)
  end

  private

  def comment_params
    params.require(:comment).permit(:response)
  end
end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy, :vote, :unvote, :flag]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :vote, :unvote, :flag]
  # impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all.order('created_at DESC')
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    @tags = @snippet.tags
    @updates = @snippet.snippets
    @parent = @snippet.snippet
    if user_signed_in? 
      if @snippet.user and current_user.id != @snippet.user.id 
        impressionist(@snippet)
      end
    else 
      impressionist(@snippet)
    end
  end

  # GET /snippets/new
  def new
    @snippet =  current_user.snippets.build
    @tags = Tag.all
    if params[:snippet_id]
      @parent = true
      @snippet =  Snippet.find(params[:snippet_id])
    end
  end

  # GET /snippets/1/edit
  def edit
    @tags = Tag.all
  end

  # POST /snippets
  # POST /snippets.json
  def create
    puts snippet_params
    if params[:snippet_id]
    @parent = Snippet.find(params[:snippet_id])
    @snippet = @parent.snippets.build(snippet_params)
    @snippet.user_id = current_user.id
    else 
    @snippet = current_user.snippets.build(snippet_params)
    end
    @snippet.username = current_user.name
    params[:tags].each do |tag|
      @snippet.tags << Tag.find(tag)
    end
    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else 
        puts @snippet.errors.to_json
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    @snippet.liked_by current_user
    respond_to do |format|
      format.html{redirect_back fallback_location: root_path}
      format.js{render layout:false}
    end
  end

  def unvote
    @snippet.unliked_by current_user
    respond_to do |format|
      format.html{redirect_back fallback_location: root_path}
      format.js{render layout:false}
    end
  end

  def outdated
    @snippet.liked_by current_user
    respond_to do |format|
      format.html{redirect_back fallback_location: root_path}
      format.js{render layout:false}
    end
  end

  def notoutdated
    @snippet.unliked_by current_user
    respond_to do |format|
      format.html{redirect_back fallback_location: root_path}
      format.js{render layout:false}
    end
  end

  def flag
    puts 'mail sent'
    FlagSnippetMailer.flag_snippet(current_user, @snippet).deliver
    
    respond_to do |format|
      format.html{redirect_back fallback_location: root_path, notice: 'Message sent to admin. Actions would be taken'}
      format.js{render layout:false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def snippet_params
      params.require(:snippet).permit(:title, :common, :beginner, :expert, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def verbose_date(date) 
    date.strftime('%B %d %Y')
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <figure class="media-left">
      <p class="image is-48x48 user-thumb">
        <%= gravatar_image_tag(comment.user.email.gsub('spam', 'mdeering'), alt: comment.user.name, gravatar: {size: 48})%>
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.name %></strong>
          <div><%= comment.response %></div>
        </p>
      </div>
    </div>
    <% if(user_signed_in? && (current_user.id == comment.user_id))%>
      <%= link_to 'delete', [comment.snippet, comment], method: :delete, class: "button is-danger", data: {confirm: "are you sure you want to delete this comment?"}%>
    <%end%>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@snippet, @snippet.comments.build]) do |f| %>

  <div class="field">
    <div class="control">
      <%= f.input :response, input_html: { class: "textarea" }, wrapper: false, label_html: {class: "label"} %>
    </div>
  </div>

  <%= f.button :submit, 'Leave a reply', class: 'button is-primary'%>
<%end%>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code Snip Save</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=devide-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice]%>
    <div class="notification is-primary global-notification">
      <p class="notice">
        <%= notice %>
      </p>
    </div>
  <%end%>
  <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert">
        <%= alert %>
      </p>
    </div>
  <%end%>

  <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to root_path, class:"navbar-item" do %>
        <h1 class="title is-5 has-text-white">Home</h1>
      <%end%>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div id="navbar" class="navbar-menu">
      <div class="navbar-start">
        <div class="navbar-item">
          <p class="control">
            <%= link_to 'Snips', root_path, class:"button is-dark"%>
          </p>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <% if user_signed_in? %>
            <p class="control">
              <%= link_to new_snippet_path, class: "button is-primary" do%>
                <span class="icon is-small"><i class="fa fa-upload"></i></span>
                <span>New Snip</span>
              <%end%>
            </p>
            <p class="control">
              <%= link_to current_user.name, edit_user_registration_path, class: "button is-dark"%>
            </p>
            <p class="control">
              <%= link_to "log out", destroy_user_session_path, method: :delete, class: "button is-dark"%>
            </p>
            <%else%>
            <p class="control">
              <%= link_to "sign in", new_user_session_path, class: "button is-dark"%>
            </p>
            <p class="control">
              <%= link_to "sign up", new_user_registration_path, class: "button is-dark"%>
            </p>
          <%end%>
        </div>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/snippets/_form.html.erb
<% if @parent == true %>

<%= simple_form_for([@snippet, @snippet.snippets.build]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>
  <div class="form-inputs">
  <label>Common Code</label>
    <%= f.text_area :common , class: 'editor'%>
  </div>
  <div class="form-inputs">
  <label>Beginner Code</label>
    <%= f.text_area :beginner , class: 'editor'%>
  </div>
  <div class="form-inputs">
  <label>Expert Code</label>
    <%= f.text_area :expert , class: 'editor'%>
  </div>
 
  <%= select_tag 'tags[]', options_for_select(@tags.map{|t| [t.name, t.id]}, @snippet.tags.pluck(:id)), :multiple => true %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<%else %>
<%= simple_form_for(@snippet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>
  <div class="form-inputs">
  <label>Common Code</label>
    <%= f.text_area :common , class: 'editor'%>
  </div>
  <div class="form-inputs">
  <label>Beginner Code</label>
    <%= f.text_area :beginner , class: 'editor'%>
  </div>
  <div class="form-inputs">
  <label>Expert Code</label>
    <%= f.text_area :expert , class: 'editor'%>
  </div>
 
 <%if @tags%>
  <%= select_tag 'tags[]', options_for_select(@tags.map{|t| [t.name, t.id]}, @snippet.tags.pluck(:id)), :multiple => true %>
  <%end%>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<% end %>

<script>
$('#snippet_expert, #snippet_common, #snippet_beginner').ace({theme: 'dawn', lang: 'javascript'})
</script>

app/views/snippets/_hero.html.erb
<% if !user_signed_in? %>
  <section class="hero is-dark">
    <div class="hero-body">
      <div class="container has-text-centered">
        <h1 class="title is-size-5">
          What are you learning? <span class="has-text-grey-light">Code Snip Save is where you can learn how to advance your skills.. 
        </h1>
        <div class="content">
          <%= link_to "login", new_user_session_path, class: "button is-primary"%>
        </div>
      </div>
    </div>
  </section>
<%end%>

app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Snippets</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snippets.each do |snippet| %>
      <tr>
        <td><%= snippet.title %></td>
        <td><%= link_to 'Show', snippet %></td>
        <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
        <td><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<div class="section">
  <div class="container">
    <h1 class="title is-3"><%= @snippet.title %></h1>
    <div class="columns">
      <div class="column is-8">
        <span class="by has-text-grey-light">by</span>
        <div class="user-thumb">
         <%if @snippet.user%>
          <%= gravatar_image_tag(@snippet.user.email.gsub('spam', 'mdeering'), alt: @snippet.user.name, gravatar: {size:20})%>
          <%else%>
          <% if  @snippet.username%> <%= @snippet.username%> <%else%> anon <%end%>
          <%end%>
        </div>
   <% if @parent %>
           <h1>Realted to :  <%= link_to @parent.title, snippet_path(@parent.id) %></h1>
            <%end%>
        <div class="user-name has-text-weight-bold"><% if  @snippet.username%> <%= @snippet.username%> <%else%> anon <%end%></div>
        <div class="shot-time"><span class="has-text-grey-light">created</span>
        <span class="has-text-weight-semibold">
          <%= verbose_date(@snippet.created_at)%>
        </span>
      </div>
    </div>
    </div>

    <div class="columns">
      <div class="column is-8">
        <div class="shot-container">
          <div class="shot-full">
           <%=text_area :snippet, :common, class: 'editor', disabled: 'disabled' %>
          </div>

          <% if user_signed_in? && (current_user.id == @snippet.user_id) %>
            <div class="buttons has-addons">
              <%= link_to 'Edit', edit_snippet_path(@snippet), class: "button"%>
            </div>
          <%end%>

          <div class="content">
            
            <%=text_area :snippet, :beginner, class: 'editor', disabled: 'disabled' %>
          </div>
          <div class="content">
            
            <%=text_area :snippet, :expert, class: 'editor', disabled: 'disabled' %>
          </div>
          <div class="content">
            
            <%@tags.each do |tag| %>
            <%= tag.name %>
            <%end%>

           
          </div>

          <div>
          <h1>Updates</h1>
           <%@updates.each do |snip| %>
            <%= link_to snip.title, snippet_path(snip.id) %>
            <%end%>
            </div>

         

        <div class="shot-time"><span class="has-text-grey-light">Updated</span>
        <span class="has-text-weight-semibold">
          <%= verbose_date(@snippet.updated_at)%>
        </span>
          
          <section class="comments">
            <h2 class="subtitle is-5"><%= pluralize(@snippet.comments.count, "Comment")%></h2>

            <%= render @snippet.comments %>
            <hr/>
            <% if user_signed_in?%>
              <div class="comment-form">
                <h3 class="subtitle is-3">Leave a reply</h3>
                <%= render 'comments/form' %>
              </div>
            <%else%>
              <div class="content"><%= link_to 'Sign in', new_user_session_path %> to leave a comment.</div>
            <%end%>
          </section>

      </div>
    </div>

    <div class="column is-3 is-offset-1">
      <div class="nav panel show-shot-analytics">
        <div class="panel-block views data">
          <span class="icon"><i class="fa fa-eye"></i></span>
          <%= pluralize(@snippet.impressionist_count, 'view') %>
        </div>

        <div class="panel-block comments data">
          <span class="icon"><i class="fa fa-comment"></i></span>
          <%= pluralize(@snippet.comments.count, 'comment') %>
        </div>

        <div class="panel-block likes data">
            <%if user_signed_in?%>
             <% if current_user.id == @snippet.user_id %>
                <span class="like_shot">
                <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                <span class="vote_count"><%= pluralize(@snippet.get_likes.size, 'Vote') %></span>
                </span>
              <%else%>
                <% if current_user.liked? @snippet %>
                  <%= link_to unvote_snippet_path(@snippet), method: :put, class: "unlike_shot" do %>
                    <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                    <span class="vote_count"><%= pluralize(@snippet.get_likes.size, 'Vote') %></span>
                  <%end%>
                <%else%>
                  <%= link_to vote_snippet_path(@snippet), method: :put, class: "like_shot" do %>
                  <span class="icon"><i class="fa fa-heart"></i></span>
                  <span class="vote_count"><%= pluralize(@snippet.get_likes.size, 'Vote') %></span>
                  <%end%>
                <%end%>
              <%end%>
            <%else%>
                <%= link_to vote_snippet_path(@snippet), method: :put, class: "like_shot" do %>
                <span class="icon"><i class="fa fa-heart"></i></span>
                <span class="vote_count"><%= pluralize(@snippet.get_likes.size, 'Vote') %></span>
              <%end%>
            <%end%>
        </div>

        <div class="panel-block likes data">
            <%if user_signed_in?%>
             <% if current_user.id == @snippet.user_id %>
                <span class="like_shot">
                <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                <span class="vote_count"><%= pluralize(@snippet.get_likes.size, 'Outdated Vote') %></span>
                </span>
              <%else%>
                <% if current_user.liked? @snippet %>
                  <%= link_to unvote_snippet_path(@snippet), method: :put, class: "unlike_shot" do %>
                    <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                    <span class="vote_count"><%= pluralize(@snippet.get_likes.size, 'Outdated Vote') %></span>
                  <%end%>
                <%else%>
                  <%= link_to vote_snippet_path(@snippet), method: :put, class: "like_shot" do %>
                  <span class="icon"><i class="fa fa-heart"></i></span>
                  <span class="vote_count"><%= pluralize(@snippet.get_likes.size, 'Outdated Vote') %></span>
                  <%end%>
                <%end%>
              <%end%>

            <%else%>
                <%= link_to vote_snippet_path(@snippet), method: :put, class: "like_shot" do %>
                <span class="icon"><i class="fa fa-heart"></i></span>
                <span class="vote_count"><%= pluralize(@snippet.get_likes.size, 'Outdated Vote') %></span>
              <%end%>
            <%end%>
            
        </div>

              <div>
              <%= link_to 'flag snippet', flag_snippet_path(@snippet), method: :post %>
              </div>

      </div>
    </div>
  </div>


<script>
  $('#snippet_expert, #snippet_common, #snippet_beginner').ace({theme: 'dawn', lang: 'javascript'})
</script>